//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dokumentooborot6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч утверж док.
    /// </summary>
    // *** Start programmer edit section *** (ТЧУтвержДок CustomAttributes)

    // *** End programmer edit section *** (ТЧУтвержДок CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч утверж док")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧУтвержДокE", new string[] {
            "УтверждениеДок as \'Утверждение док\'",
            "УтверждениеДок.Дата as \'Дата\'"}, Hidden=new string[] {
            "УтверждениеДок.Дата"})]
    [MasterViewDefineAttribute("ТЧУтвержДокE", "УтверждениеДок", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Дата")]
    public class ТЧУтвержДок : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Dokumentooborot6.УтверждениеДок fУтверждениеДок;
        
        private IIS.Dokumentooborot6.ДокументНеУт fДокументНеУт;
        
        // *** Start programmer edit section *** (ТЧУтвержДок CustomMembers)

        // *** End programmer edit section *** (ТЧУтвержДок CustomMembers)

        
        /// <summary>
        /// Т ч утверж док.
        /// </summary>
        // *** Start programmer edit section *** (ТЧУтвержДок.УтверждениеДок CustomAttributes)

        // *** End programmer edit section *** (ТЧУтвержДок.УтверждениеДок CustomAttributes)
        [PropertyStorage(new string[] {
                "УтверждениеДок"})]
        [NotNull()]
        public virtual IIS.Dokumentooborot6.УтверждениеДок УтверждениеДок
        {
            get
            {
                // *** Start programmer edit section *** (ТЧУтвержДок.УтверждениеДок Get start)

                // *** End programmer edit section *** (ТЧУтвержДок.УтверждениеДок Get start)
                IIS.Dokumentooborot6.УтверждениеДок result = this.fУтверждениеДок;
                // *** Start programmer edit section *** (ТЧУтвержДок.УтверждениеДок Get end)

                // *** End programmer edit section *** (ТЧУтвержДок.УтверждениеДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧУтвержДок.УтверждениеДок Set start)

                // *** End programmer edit section *** (ТЧУтвержДок.УтверждениеДок Set start)
                this.fУтверждениеДок = value;
                // *** Start programmer edit section *** (ТЧУтвержДок.УтверждениеДок Set end)

                // *** End programmer edit section *** (ТЧУтвержДок.УтверждениеДок Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Dokumentooborot6.ДокументНеУт.
        /// </summary>
        // *** Start programmer edit section *** (ТЧУтвержДок.ДокументНеУт CustomAttributes)

        // *** End programmer edit section *** (ТЧУтвержДок.ДокументНеУт CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ДокументНеУт"})]
        public virtual IIS.Dokumentooborot6.ДокументНеУт ДокументНеУт
        {
            get
            {
                // *** Start programmer edit section *** (ТЧУтвержДок.ДокументНеУт Get start)

                // *** End programmer edit section *** (ТЧУтвержДок.ДокументНеУт Get start)
                IIS.Dokumentooborot6.ДокументНеУт result = this.fДокументНеУт;
                // *** Start programmer edit section *** (ТЧУтвержДок.ДокументНеУт Get end)

                // *** End programmer edit section *** (ТЧУтвержДок.ДокументНеУт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧУтвержДок.ДокументНеУт Set start)

                // *** End programmer edit section *** (ТЧУтвержДок.ДокументНеУт Set start)
                this.fДокументНеУт = value;
                // *** Start programmer edit section *** (ТЧУтвержДок.ДокументНеУт Set end)

                // *** End programmer edit section *** (ТЧУтвержДок.ДокументНеУт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧУтвержДокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧУтвержДокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧУтвержДокE", typeof(IIS.Dokumentooborot6.ТЧУтвержДок));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧУтвержДок.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧУтвержДок CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧУтвержДок CustomAttributes)
    public class DetailArrayOfТЧУтвержДок : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Dokumentooborot6.DetailArrayOfТЧУтвержДок members)

        // *** End programmer edit section *** (IIS.Dokumentooborot6.DetailArrayOfТЧУтвержДок members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧУтвержДок by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧУтвержДок.
        /// </summary>
        public DetailArrayOfТЧУтвержДок(IIS.Dokumentooborot6.ДокументНеУт fДокументНеУт) : 
                base(typeof(ТЧУтвержДок), ((ICSSoft.STORMNET.DataObject)(fДокументНеУт)))
        {
        }
        
        public IIS.Dokumentooborot6.ТЧУтвержДок this[int index]
        {
            get
            {
                return ((IIS.Dokumentooborot6.ТЧУтвержДок)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Dokumentooborot6.ТЧУтвержДок dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
